spring:
  datasource:
    url: jdbc:mysql://localhost:3309/dome?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin #root
    password: in2pass #1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: in2test
      password: in2pass
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/EAAProvider
#          resource-id: oidc4vci-client
#          resource-secret: f0GZ3F5Okjgptrrf9WMjmlkqRK5kyTF1
          did: did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa
          token-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/verifiable-credential/${spring.security.oauth2.resourceserver.jwt.did}/token
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8083

in2:
  openapi:
    local-url: http://localhost:8083
    dev-url: https://walletapidev.in2.es

app:
  url:
    api: http://localhost:8083
    orion_context_broker: http://localhost:1026/v2/entities