spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: in2test
      password: in2pass
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_URL_KEYCLOAK}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: ${SERVER_PORT}

in2:
  openapi:
    local-url: http://localhost:8083
    dev-url: https://walletapidev.in2.es

app:
  url:
    api: ${APP_URL_API}
    orion_context_broker: ${APP_URL_ORION}