spring:
  datasource:
    url: jdbc:mysql://localhost:3309/dome?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin #root
    password: in2pass #1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: in2test
      password: in2pass
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/EAAProvider
#          resource-id: oidc4vci-client
#          resource-secret: f0GZ3F5Okjgptrrf9WMjmlkqRK5kyTF1
          did: did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa
          token-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/verifiable-credential/${spring.security.oauth2.resourceserver.jwt.did}/token
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8083

# Documentation
springdoc:
  # swagger-ui custom path
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  show-actuator: true
  use-management-port: true

# open all Actuator endpoints
management:
  server:
    port: 9093
  endpoints:
    web:
      exposure:
        include: "*" # openapi, swagger-ui

app:
  url:
    api: http://localhost:8083

fiware:
  url: http://localhost:1026